name: Build macOS installer
on:
  push:
    branches:
      - "main"
      - "old-main"
  pull_request: {}
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-11
        go:
          - 1.17
    steps:
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
        timeout-minutes: 30
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: "Import code signing certificate"
        uses: devbotsxyz/import-signing-certificate@main
        with:
          certificate-data: ${{ secrets.MACOS_APPLICATION_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.MACOS_APPLICATION_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
          keychain-name: "crc-keychain"
      - name: "Import product signing certificate"
        uses: devbotsxyz/import-signing-certificate@main
        with:
          certificate-data: ${{ secrets.MACOS_INSTALLER_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.MACOS_INSTALLER_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
          keychain-name: "crc-keychain"
      - name: Build macOS installer
        env:
          CODESIGN_IDENTITY: "Developer ID Application: Christophe Fergeau (GSP9DR7D3R)"
          PRODUCTSIGN_IDENTITY: "Developer ID Installer: Christophe Fergeau (GSP9DR7D3R)"
        run: make out/macos-universal/crc-macos-installer.pkg
      - name: Install crc pkg
        run: sudo installer -pkg out/macos-universal/crc-macos-installer.pkg -target /
      - name: Set podman preset as part of config
        run: crc config set preset podman
      - name: Run crc setup command
        run: crc setup
      - name: Wait 10 sec for the daemon to serve
        run: sleep 10
      - name: Run crc with podman preset
        run: crc start
      - name: Upload macOS installer artifact
        uses: actions/upload-artifact@v2
        with:
          name: macOS Installer (${{ matrix.os }})
          path: "./out/macos-amd64/crc-macos-amd64.pkg"
